databaseChangeLog:
  - changeSet:
      id: create-subscription-form-status-enum
      author: system
      comment: Create enum type for subscription form status
      changes:
        - sql:
            sql: |
              CREATE TYPE subscription_form_status AS ENUM ('DRAFT','PUBLISHED','DISABLED','ARCHIVED');
      rollback:
        - sql:
            sql: DROP TYPE IF EXISTS subscription_form_status;

  - changeSet:
      id: create-subscription-forms-table
      author: system
      comment: Create subscription_forms table for storing form configurations
      changes:
        - createTable:
            tableName: subscription_forms
            columns:
              - column:
                  name: id
                  type: uuid
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: varchar(120)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: text
              - column:
                  name: header
                  type: varchar(120)
                  constraints:
                    nullable: false
              - column:
                  name: input_placeholder
                  type: varchar(120)
                  constraints:
                    nullable: false
              - column:
                  name: button_text
                  type: varchar(120)
                  constraints:
                    nullable: false
              - column:
                  name: button_color
                  type: varchar(7)
                  constraints:
                    nullable: false
              - column:
                  name: background_color
                  type: varchar(7)
                  constraints:
                    nullable: false
              - column:
                  name: text_color
                  type: varchar(7)
                  constraints:
                    nullable: false
              - column:
                  name: button_text_color
                  type: varchar(7)
                  constraints:
                    nullable: false
              - column:
                  name: status
                  type: subscription_form_status
                  defaultValue: DRAFT
                  constraints:
                    nullable: false
              - column:
                  name: workspace_id
                  type: uuid
                  constraints:
                    nullable: false
              - column:
                  name: created_by
                  type: varchar(50)
                  constraints:
                    nullable: false
                  defaultValue: 'system'
              - column:
                  name: created_at
                  type: timestamp with time zone
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_by
                  type: varchar(50)
                  constraints:
                    nullable: true
              - column:
                  name: updated_at
                  type: timestamp with time zone
                  constraints:
                    nullable: true

        - createIndex:
            indexName: idx_subscription_forms_workspace
            tableName: subscription_forms
            columns:
              - column:
                  name: workspace_id

        - createIndex:
            indexName: idx_subscription_forms_created_at
            tableName: subscription_forms
            columns:
              - column:
                  name: created_at
                  descending: true

      rollback:
        - dropTable:
            tableName: subscription_forms
