databaseChangeLog:
  - changeSet:
      id: add-input-text-color
      author: system
      comment: Add input text color for email input field
      changes:
        - addColumn:
            tableName: subscription_forms
            columns:
              - column:
                  name: input_text_color
                  type: varchar(7)
                  defaultValue: '#000000'
                  constraints:
                    nullable: false

      rollback:
        - dropColumn:
            tableName: subscription_forms
            columnName: input_text_color
