# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
early_access: true
inheritance: true
language: en-US

tone_instructions: >-
  Be direct, constructive, and educational. Focus on architectural patterns, security, and maintainability.
  Flag violations of Clean Architecture principles assertively.

reviews:
  profile: assertive
  request_changes_workflow: true
  high_level_summary_in_walkthrough: true
  fail_commit_status: true
  collapse_walkthrough: true
  auto_apply_labels: true
  auto_assign_reviewers: true
  auto_title_instructions: >-
    Add a prefix to indicate what kind of release this pull request corresponds to. For reference,
    see https://www.conventionalcommits.org/  Available types:  - feat: A new feature  - fix: A bug
    fix  - docs: Documentation only changes  - style: Changes that do not affect the meaning of the
    code (white-space, formatting, missing semi-colons, etc)  - refactor: A code change that neither
    fixes a bug nor adds a feature  - perf: A code change that improves performance  - test: Adding
    missing tests or correcting existing tests  - build: Changes that affect the build system or
    external dependencies (example scopes: gulp, broccoli, npm)  - ci: Changes to our CI
    configuration files and scripts (example scopes: Travis, Circle, BrowserStack, SauceLabs)  -
    chore: Other changes that don't modify src or test files  - revert: Reverts a previous commit
  path_filters:
    - '!docs/src/content/docs/structure.md'
  # Path-specific instructions
  path_instructions:
    # Backend - DOMAIN LAYER (CRITICAL - NO FRAMEWORK DEPENDENCIES)
    - path: 'server/engine/src/main/kotlin/**/domain/**'
      instructions: |
        🚨 CRITICAL: This is the DOMAIN LAYER - the heart of Clean Architecture.

        STRICT REQUIREMENTS:
        - MUST be pure Kotlin with ZERO framework dependencies
        - NO imports from: Spring, R2DBC, Jakarta, Hibernate, or ANY framework
        - Contains ONLY: Entities, Value Objects, Repository Interfaces, Domain Events, Exceptions
        - Should depend ONLY on Kotlin stdlib and other domain classes

        FLAG AS CRITICAL VIOLATION:
        - Any import from `org.springframework.*`
        - Any import from `io.r2dbc.*`
        - Any import from `jakarta.*`
        - Any annotation from frameworks (`@Component`, `@Entity`, `@Table`, etc.)

        SEE: `.agents/skills/hexagonal-architecture/SKILL.md` for details

    # Backend - APPLICATION LAYER (CQRS USE CASES)
    - path: 'server/engine/src/main/kotlin/**/application/**'
      instructions: |
        This is the APPLICATION LAYER - orchestrates business logic using CQRS.

        REQUIREMENTS:
        - Framework-agnostic business logic
        - CQRS pattern enforced:
          * Commands (writes): CreateXCommand → CreateXCommandHandler → XCreator service
          * Queries (reads): FindXQuery → FindXQueryHandler → XFinder service
        - Handlers are THIN: receive command/query, delegate to service
        - Services contain actual business logic and orchestration
        - Can import domain classes, NO infrastructure imports
        - Must use domain repository interfaces, never implementations

        FLAG VIOLATIONS:
        - Handlers with business logic (should delegate to services)
        - Direct calls to infrastructure layer
        - Missing Command/Query pattern
        - Controllers called directly from application layer

        SEE: `.agents/skills/hexagonal-architecture/SKILL.md` and `AGENTS.md`

    # Backend - INFRASTRUCTURE LAYER
    - path: 'server/engine/src/main/kotlin/**/infrastructure/**'
      instructions: |
        This is the INFRASTRUCTURE LAYER - implements technical concerns.

        REQUIREMENTS:
        - Implements domain repository interfaces (never expose implementations)
        - Controllers call handlers, NEVER services directly
        - Controllers are THIN: validate input, call handler, return response
        - NEVER expose database entities through API - always use DTOs
        - HTTP endpoints follow REST conventions (see `AGENTS.md` and `.agents/skills/spring-boot/SKILL.md`)
        - R2DBC repositories implement domain interfaces

        FLAG VIOLATIONS:
        - Controllers with business logic
        - Direct service calls from controllers (should go through handlers)
        - Database entities exposed in API responses
        - Missing DTO mapping
        - Non-RESTful endpoint design

        SEE: `.agents/skills/spring-boot/SKILL.md` and `.agents/skills/hexagonal-architecture/SKILL.md`

    # Backend - Kotlin General
    - path: 'server/**/*.kt'
      instructions: |
        Kotlin Code Review - Enforce conventions from `.agents/skills/kotlin/SKILL.md`

        CRITICAL VIOLATIONS:
        - Using `!!` operator (use `?.`, `?:`, `requireNotNull()`, or sealed classes)
        - Using `var` when `val` would work
        - Blocking in reactive flows (avoid `.block()` in application code)
        - Not using `suspend` for I/O operations
        - Logging sensitive data (passwords, tokens, PII)

        VERIFY:
        - Proper use of coroutines and structured concurrency
        - Null safety patterns
        - Immutability preferred
        - Proper error handling with sealed classes or Result<T>
        - Repository methods are suspend functions

    # Backend - Tests
    - path: 'server/engine/src/test/**'
      instructions: |
        Backend Test Review - Enforce `AGENTS.md` testing conventions

        REQUIREMENTS:
        - Test names use backticks: `should do X when Y`
        - Unit tests: @UnitTest annotation, MockK for mocks, Kotest for assertions
        - Integration tests: @IntegrationTest, Testcontainers for PostgreSQL
        - Arrange-Act-Assert structure clearly visible
        - Test behavior, not implementation
        - Proper use of `runTest` for coroutine testing

        FLAG VIOLATIONS:
        - Missing test coverage for new features
        - Poor test naming
        - Testing implementation details instead of behavior
        - Missing assertions

    # Frontend - Vue Components (all apps)
    - path: 'client/apps/**/src/**/*.vue'
      instructions: |
        Vue Component Review - Enforce `.agents/skills/vue/SKILL.md` conventions

        REQUIREMENTS:
        - Use Composition API with `<script setup lang="ts">`
        - Props: `defineProps<Props>()` with TypeScript, `withDefaults()` for defaults
        - Events: `defineEmits<{ (e: 'event', value: Type): void }>()`
        - Use Shadcn-Vue components from `@/components/ui` when possible
        - Co-locate styles in `<style scoped>` using Tailwind design tokens

        VERIFY:
        - Accessibility: semantic HTML, ARIA attributes, keyboard navigation
        - Form validation: Vee-Validate + Zod with manual blur validation
        - No hardcoded colors (use design tokens from Tailwind CSS 4)
        - Proper use of composables for reusable logic

        FLAG VIOLATIONS:
        - Options API usage
        - Hardcoded colors (use bg-background, text-foreground, etc.)
        - Missing accessibility attributes
        - Complex logic in components (should be in composables)

    # Frontend - TypeScript (all apps and packages)
    - path: 'client/**/*.ts'
      instructions: |
        TypeScript Review - Enforce `.agents/skills/typescript/SKILL.md` conventions

        CRITICAL VIOLATIONS:
        - Using `any` type (use `unknown` and narrow, or proper types)
        - Missing explicit types on function parameters or return values
        - Using `default export` (prefer named exports)

        REQUIREMENTS:
        - Explicit types for all function parameters and return values
        - Use `type` over `interface` unless declaration merging needed
        - Use TypeScript utility types (Partial, Pick, Omit, Record)
        - Composables: `useXxx.ts` pattern, return reactive values
        - Stores: `useXxxStore` naming, strongly typed state/getters/actions

    # Frontend - Unit/Integration Tests
    - path: 'client/apps/**/src/**/__tests__/**'
      instructions: |
        Frontend Unit/Integration Test Review - Enforce `AGENTS.md` testing conventions

        REQUIREMENTS:
        - Vitest for unit tests
        - @testing-library/vue for component tests
        - Test behavior, not implementation
        - Use user-facing queries when possible (getByRole, getByLabelText)
        - Clear test naming: 'should X when Y' or descriptive names
        - Arrange-Act-Assert structure

        FLAG VIOLATIONS:
        - Testing implementation details (internal state, methods)
        - Poor test isolation (shared mutable state)
        - Missing assertions or unclear expectations
        - Brittle selectors in component tests

    # Frontend - UI Package (Shadcn-Vue components)
    - path: 'client/packages/ui/**/*.vue'
      instructions: |
        UI Package Component Review - Shared design system components

        CRITICAL: These are SHARED components used across all apps.

        REQUIREMENTS:
        - Must use design tokens from `.agents/skills/tailwind-4/SKILL.md`
        - NO hardcoded colors - use semantic tokens (bg-background, text-foreground, etc.)
        - Props should be flexible and well-typed
        - Maintain Shadcn-Vue API compatibility
        - Accessibility is CRITICAL (ARIA, keyboard nav, focus management)
        - Comprehensive prop validation with TypeScript

        FLAG VIOLATIONS:
        - Hardcoded color values or Tailwind color classes (bg-gray-900, etc.)
        - Breaking changes to existing component APIs
        - Missing accessibility attributes
        - App-specific logic (should be generic and reusable)
        - Poor TypeScript types on props

        SEE: `.agents/skills/tailwind-4/SKILL.md` for token usage

    # Frontend - Astro Components (marketing site)
    - path: 'client/apps/marketing/**/*.astro'
      instructions: |
        Astro Component Review - Enforce `.agents/skills/astro/SKILL.md` conventions

        REQUIREMENTS:
        - Server-first approach: minimize client-side JavaScript
        - Use framework components (Vue) ONLY for interactive islands with `client:*` directives
        - Proper `client:*` directive usage:
          * `client:load` - immediate hydration (rare)
          * `client:idle` - when browser idle (interactive elements)
          * `client:visible` - when in viewport (below fold)
        - Component-scoped styles, use Tailwind design tokens
        - SEO: proper meta tags, structured data, semantic HTML
        - Optimize images with Astro's `<Image />` component

        FLAG VIOLATIONS:
        - Unnecessary client-side JavaScript
        - Missing `client:*` directive on interactive components
        - Non-optimized images
        - Hardcoded colors (use Tailwind tokens)
        - Poor SEO practices

    # Frontend - E2E Tests (per-app)
    - path: 'client/apps/**/e2e/**'
      instructions: |
        Playwright E2E Test Review - Enforce `AGENTS.md` and `.agents/skills/playwright/SKILL.md` conventions

        REQUIREMENTS:
        - Use user-facing locators: `getByRole`, `getByLabel`, `getByText`
        - NO XPath, CSS class selectors, or `data-testid` (unless absolutely necessary)
        - Use web-first assertions: `await expect(locator).toBeVisible()`
        - NO manual waits or sleeps (use auto-retry assertions)
        - Use `test.step()` for multi-step flows
        - Test user journeys, not implementation details
        - HAR fixtures for auth flows in `fixtures/har/` to speed up tests

        FLAG VIOLATIONS:
        - Brittle selectors (CSS classes, IDs)
        - Manual waits (page.waitForTimeout)
        - Testing implementation details
        - Missing accessibility in locators

    # Database Migrations
    - path: 'server/engine/src/main/resources/db/changelog/**'
      instructions: |
        Liquibase Migration Review - Enforce database conventions from `AGENTS.md`

        REQUIREMENTS:
        - Follow naming: `NNN-feature.yaml`, `NNNa-triggers.yaml`, `NNNb-rls.yaml`
        - UUID for ALL primary keys (never auto-increment integers)
        - RLS policies for multi-tenant tables with `tenant_id` column
        - Indexes on RLS policy columns for performance
        - NEVER modify applied migrations (create new ones instead)
        - Include rollback for complex changes

        FLAG VIOLATIONS:
        - Non-UUID primary keys
        - Missing RLS on multi-tenant tables
        - Missing indexes on foreign keys or RLS columns
        - Modifying existing migrations
        - Poor naming conventions

  # Labeling instructions
  labeling_instructions:
    - label: 'backend'
      instructions: 'Apply when PR contains changes to Kotlin code, Spring Boot, database, or backend infrastructure'

    - label: 'frontend'
      instructions: 'Apply when PR contains changes to TypeScript, Vue, Astro, or frontend assets'

    - label: 'architecture'
      instructions: 'Apply when PR introduces changes to domain models, application layer structure, or architectural patterns'

    - label: 'security'
      instructions: 'Apply when PR touches authentication, authorization, RLS, input validation, or security-related code'

    - label: 'database'
      instructions: 'Apply when PR includes database migrations, schema changes, or repository implementations'

    - label: 'documentation'
      instructions: 'Apply when PR updates .agents/skills/ docs, README files, AGENTS.md, or API documentation'

    - label: 'testing'
      instructions: 'Apply when PR adds or modifies tests (unit, integration, or E2E)'

    - label: 'breaking-change'
      instructions: 'Apply when PR introduces breaking changes to APIs, database schema, or public interfaces'

  auto_review:
    enabled: true
    drafts: true
    auto_incremental_review: true

  # Pre-merge checks
  pre_merge_checks:
    title:
      mode: error
      requirements: >-
        Title must follow Conventional Commits format with optional emoji.
        Examples: 'feat(auth): add password reset', 'fix(api): correct pagination'

    description:
      mode: warning

    issue_assessment:
      mode: warning

    custom_checks:
      - name: 'Clean Architecture Compliance'
        mode: error
        instructions: |
          Verify that Clean Architecture principles are followed:
          1. Domain layer has NO framework dependencies
          2. Application layer only depends on domain
          3. Infrastructure implements domain interfaces
          4. CQRS pattern is used for all operations
          5. Controllers call handlers, not services directly

      - name: 'Security Review'
        mode: error
        instructions: |
          Check for security issues:
          1. No SQL injection (use parameterized queries)
          2. No XSS vulnerabilities (use textContent, not innerHTML with user data)
          3. Input validation present on all user-facing endpoints
          4. Authentication/authorization properly enforced
          5. No secrets committed to repository
          6. RLS policies present for multi-tenant tables

      - name: 'Test Coverage'
        mode: warning
        instructions: |
          Ensure adequate test coverage:
          1. Unit tests for all new business logic
          2. Integration tests for new endpoints
          3. E2E tests for critical user flows (if applicable)
          4. Tests follow naming conventions (backticks for Kotlin, descriptive for TS)

  # Enable relevant linters
  tools:
    biome:
      enabled: true
    detekt:
      enabled: true
      config_file: 'config/detekt.yml'
    gitleaks:
      enabled: true
    yamllint:
      enabled: true
    hadolint:
      enabled: true
    markdownlint:
      enabled: true
    github-checks:
      enabled: true
      timeout_ms: 90000

knowledge_base:
  code_guidelines:
    enabled: true
    filePatterns:
      - '.agents/skills/**/*.md'
      - 'AGENTS.md'

  learnings:
    scope: auto

  issues:
    scope: auto

  pull_requests:
    scope: auto

  linear:
    usage: auto
    team_keys:
      - COD

chat:
  auto_reply: true
  integrations:
    linear:
      usage: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions:
      - path: 'server/**/*.kt'
        instructions: |
          Generate KDoc for public APIs:
          - Brief description of purpose
          - @param for all parameters with clear descriptions
          - @return for return value
          - @throws for exceptions
          - @sample for complex functions
          - Follow conventions from `.agents/skills/kotlin/SKILL.md`

      - path: 'client/**/*.ts'
        instructions: |
          Generate TSDoc/JSDoc for public APIs:
          - Brief description
          - @param for parameters with types
          - @returns with type
          - @example for complex functions
          - @throws if applicable
          - Follow conventions from `.agents/skills/typescript/SKILL.md`

  unit_tests:
    path_instructions:
      - path: 'server/**/*.kt'
        instructions: |
          Generate Kotlin tests following `AGENTS.md`:
          - Use backtick naming: `should do X when Y`
          - JUnit 5 + Kotest assertions + MockK for mocks
          - Arrange-Act-Assert structure
          - Use @UnitTest for unit tests
          - Use `runTest` for coroutine testing

      - path: 'client/**/*.ts'
        instructions: |
          Generate TypeScript tests following `AGENTS.md`:
          - Vitest for unit tests
          - @testing-library/vue for component tests
          - Test behavior, not implementation
          - Use user-facing queries when possible
