# yamllint configuration file
---
extends: default
# Note: application-test.yml is ignored because [specific reason: e.g., "it requires non-standard structure for CI overrides"]
ignore: |
  server/engine/src/test/resources/application-test.yml
rules:
  truthy:
    check-keys: true

