# yamllint configuration file
---
extends: default
ignore: |
  .yamllint.yml
  server/engine/src/test/resources/application-test.yml
  node_modules/
  build/
  client/apps/marketing/dist/
  client/apps/marketing/public/
rules:
  line-length:
    max: 250
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  document-start: disable
  truthy: disable
  comments: disable
  comments-indentation: disable

