packages:
  - client/apps/*
  - client/packages/*
  - client/config

catalog:
  '@astrojs/check': ^0.9.6
  '@astrojs/mdx': ^4.3.13
  '@astrojs/node': ^9.0.0
  '@astrojs/rss': ^4.0.14
  '@astrojs/sitemap': ^3.6.0
  '@astrojs/starlight': ^0.37.1
  '@astrojs/vue': ^5.1.3
  '@fontsource-variable/onest': 5.1.0
  '@iconify-json/heroicons': ^1.2.1
  '@iconify-json/openmoji': ^1.2.19
  '@iconify-json/ph': ^1.2.2
  '@iconify-json/tabler': ^1.2.26
  '@iconify/utils': ^2.1.33
  '@internationalized/date': ^3.10.1
  '@playwright/test': ^1.57.0
  '@sentry/astro': ^8.42.0
  '@tailwindcss/typography': ^0.5.19
  '@tailwindcss/vite': ^4.1.18
  '@tanstack/vue-table': ^8.21.3
  '@types/node': ^25.0.3
  '@unovis/ts': ^1.6.2
  '@unovis/vue': ^1.6.2
  '@vee-validate/zod': ^4.15.1
  '@vitejs/plugin-vue': ^6.0.3
  '@vitest/coverage-v8': ^4.0.16
  '@vueuse/core': ^14.1.0
  ajv: ^8.17.1
  astro: ^5.16.6
  astro-icon: ^1.1.5
  autoprefixer: ^10.4.23
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  embla-carousel-vue: ^8.6.0
  happy-dom: ^20.0.11
  lucide-vue-next: ^0.562.0
  mdast-util-to-string: ^4.0.0
  npm-run-all2: ^8.0.4
  oxlint: ^1.37.0
  postcss: ^8.5.6
  reading-time: ^1.5.0
  reka-ui: ^2.7.0
  rimraf: ^6.1.2
  semantic-release: ^25.0.2
  sharp: ^0.34.5
  stylelint: ^16.26.0
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  vaul-vue: ^0.4.1
  vee-validate: ^4.15.1
  vite: ^7.3.0
  vite-plugin-dts: ^4.5.4
  vite-tsconfig-paths: ^6.0.3
  vitest: ^4.0.16
  vue: ^3.5.26
  vue-sonner: ^2.0.9
  vue-tsc: ^3.2.1
  zod: ^3.23.8

catalogs:
  peers:
    astro: ^4.5 || ^5.0.0-beta.0
    tailwindcss: ^4.1.18
    vite: ^5.0.0 || ^6.0.0

minimumReleaseAge: 4320

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
  - sharp
