name: cvix
include:
  - ./infra/common.yml
  - ./infra/postgresql/postgresql-compose.yml
  - ./infra/keycloak/keycloak-compose.yml
services:
  landing:
    image: ghcr.io/dallay/cvix/landing:latest
    ports:
      - '443:443'
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
      REACT_APP_KEYCLOAK_URL: http://keycloak:8080/auth
      REACT_APP_KEYCLOAK_REALM: cvix
      REACT_APP_KEYCLOAK_CLIENT_ID: cvix-frontend
    networks:
      - frontend
  frontend:
    image: ghcr.io/dallay/cvix/webapp:latest
    ports:
      - '80:80'
    environment:
      REACT_APP_BACKEND_URL: http://backend:8080
      REACT_APP_KEYCLOAK_URL: http://keycloak:8080/auth
      REACT_APP_KEYCLOAK_REALM: cvix
      REACT_APP_KEYCLOAK_CLIENT_ID: cvix-frontend
    networks:
      - frontend
  backend:
    image: ghcr.io/dallay/cvix/engine:latest
    ports:
      - '8080:8080'
    environment:
      DATABASE_URL: r2dbc:postgresql://postgresql:5432/postgres
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SPRING_PROFILES_ACTIVE: dev
    networks:
      - frontend
      - backend
