name: cvix
include:
  - ./infra/common.yml
  - ./infra/postgresql/postgresql-compose.yml
  - ./infra/keycloak/keycloak-compose.yml
services:
  traefik:
    image: traefik:v3.0
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - frontend
      - backend

  landing:
    image: ghcr.io/dallay/cvix/marketing:latest
    environment:
      PUBLIC_BASE_URL_PROD: ${PUBLIC_BASE_URL_PROD}
      PUBLIC_BASE_DOCS_URL_PROD: ${PUBLIC_BASE_DOCS_URL_PROD}
      PUBLIC_SITE_URL: ${PUBLIC_SITE_URL}
      PUBLIC_BASE_WEBAPP_URL_PROD: ${PUBLIC_BASE_WEBAPP_URL_PROD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.landing.rule=Host(`landing.localhost`)"
      - "traefik.http.routers.landing.entrypoints=websecure"
      - "traefik.http.services.landing.loadbalancer.server.port=443"
    networks:
      - frontend

  frontend:
    image: ghcr.io/dallay/cvix/webapp:latest
    environment:
      BACKEND_URL: ${BACKEND_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.localhost`)"
      - "traefik.http.routers.frontend.entrypoints=web"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - frontend

  backend:
    image: ghcr.io/dallay/cvix/engine:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      OAUTH2_SERVER_URL: ${OAUTH2_SERVER_URL}
      CLIENT_ID: ${CLIENT_ID}
      CLIENT_SECRET: ${CLIENT_SECRET}
      ADMIN_CLIENT_ID: ${ADMIN_CLIENT_ID}
      ADMIN_REALM: ${ADMIN_REALM}
      ADMIN_REALM_USERNAME: ${ADMIN_REALM_USERNAME}
      ADMIN_REALM_PASSWORD: ${ADMIN_REALM_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
      CORS_ALLOWED_METHODS: ${CORS_ALLOWED_METHODS}
      CORS_ALLOWED_HEADERS: ${CORS_ALLOWED_HEADERS}
      CORS_EXPOSED_HEADERS: ${CORS_EXPOSED_HEADERS}
      CORS_ALLOW_CREDENTIALS: ${CORS_ALLOW_CREDENTIALS}
      CORS_MAX_AGE: ${CORS_MAX_AGE}
      HOSTNAME: ${HOSTNAME}
      SENDGRID_API_KEY: ${SENDGRID_API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`backend.localhost`)"
      - "traefik.http.routers.backend.entrypoints=web"
      - "traefik.http.services.backend.loadbalancer.server.port=8080"
    networks:
      - frontend
      - backend
