package com.cvix.resume.infrastructure.http

import com.cvix.common.domain.bus.Mediator
import com.cvix.common.domain.bus.command.CommandHandlerExecutionError
import com.cvix.resume.application.ResumeDocumentResponse
import com.cvix.resume.application.create.CreateResumeCommand
import com.cvix.resume.infrastructure.http.mapper.ResumeRequestMapper
import com.cvix.resume.infrastructure.http.request.CreateResumeRequest
import com.cvix.spring.boot.ApiController
import com.cvix.spring.boot.logging.LogMasker
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.security.SecurityRequirement
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import java.net.URI
import java.util.UUID
import org.slf4j.LoggerFactory
import org.springframework.http.ProblemDetail
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController

/**
 * Controller for creating new resume/CV documents.
 *
 * This controller handles the creation of resume documents within a workspace context.
 * The workspace ID is obtained from the X-Workspace-Id header.
 *
 * Uses header-based API versioning (API-Version: v1).
 *
 * ## Security Features:
 * - Requires authentication (Bearer JWT token)
 * - Requires workspace context (X-Workspace-Id header)
 * - Validates user access to workspace
 * - Uses Row-Level Security (RLS) for data isolation
 *
 * @property mediator The mediator for dispatching commands.
 * @created 20/11/25
 */
@RestController
@RequestMapping(value = ["/api"], produces = ["application/vnd.api.v1+json"])
@Tag(
    name = "Resume",
    description = "Resume/CV document management endpoints",
)
class CreateResumeController(
    mediator: Mediator,
) : ApiController(mediator) {
    /**
     * Creates a new resume/CV document.
     *
     * Creates a resume with the specified ID, title, and content within the current workspace.
     * The resume ID must be a valid UUID and should be generated by the client.
     * The workspace context is determined from the X-Workspace-Id header.
     *
     * @param id The UUID for the new resume (client-generated).
     * @param request The resume creation request containing title and content.
     * @return ResponseEntity with HTTP 201 Created and the created resume document.
     */
    @Operation(
        summary = "Create a new resume/CV document",
        description = "Creates a new resume within a workspace context. " +
            "Requires X-Workspace-Id header to specify the workspace. " +
            "The resume ID should be a UUID generated by the client.",
        security = [SecurityRequirement(name = "bearerAuth")],
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "201",
                description = "Resume created successfully - Location header contains resume URI",
                content = [Content(schema = Schema(implementation = ResumeDocumentResponse::class))],
            ),
            ApiResponse(
                responseCode = "400",
                description = "Invalid request data - Invalid resume content structure, " +
                    "missing required fields, or validation errors",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Unauthorized - Missing or invalid authentication token",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "403",
                description = "Forbidden - User does not have access to the specified workspace",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "409",
                description = "Conflict - Resume with the specified ID already exists",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "500",
                description = "Internal server error during resume creation",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
        ],
    )
    @PutMapping("/resume/{id}", consumes = ["application/json"])
    suspend fun createResume(
        @PathVariable id: UUID,
        @Valid @RequestBody request: CreateResumeRequest,
    ): ResponseEntity<ResumeDocumentResponse> {
        val safeIdMasked = LogMasker.mask(id)
        log.debug("Creating new resume: {}", safeIdMasked)

        val userId = userIdFromToken()
        val workspaceId = workspaceIdFromContext()

        val command = CreateResumeCommand(
            id = id,
            userId = userId,
            workspaceId = workspaceId,
            title = request.title,
            content = ResumeRequestMapper.toDomain(request.content),
            createdBy = userId.toString(),
        )

        val response = try {
            dispatch(command)
        } catch (e: CommandHandlerExecutionError) {
            log.error("Error creating resume/cv with ID: {}", safeIdMasked, e)
            throw e
        }

        log.info("Resume created successfully with ID: {}", safeIdMasked)

        return ResponseEntity.created(
            URI.create("/api/resume/${sanitizePathVariable(id.toString())}"),
        ).body(response)
    }

    companion object {
        private val log = LoggerFactory.getLogger(CreateResumeController::class.java)
    }
}
