package com.cvix.resume.infrastructure.http

import com.cvix.common.domain.bus.Mediator
import com.cvix.common.domain.bus.command.CommandHandlerExecutionError
import com.cvix.resume.application.ResumeDocumentResponse
import com.cvix.resume.application.create.CreateResumeCommand
import com.cvix.resume.infrastructure.http.mapper.ResumeRequestMapper
import com.cvix.resume.infrastructure.http.request.CreateResumeRequest
import com.cvix.spring.boot.ApiController
import com.cvix.spring.boot.logging.LogMasker
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.Parameter
import io.swagger.v3.oas.annotations.enums.ParameterIn
import io.swagger.v3.oas.annotations.media.Content
import io.swagger.v3.oas.annotations.media.ExampleObject
import io.swagger.v3.oas.annotations.media.Schema
import io.swagger.v3.oas.annotations.responses.ApiResponse
import io.swagger.v3.oas.annotations.responses.ApiResponses
import io.swagger.v3.oas.annotations.security.SecurityRequirement
import io.swagger.v3.oas.annotations.tags.Tag
import jakarta.validation.Valid
import java.net.URI
import java.util.UUID
import org.slf4j.LoggerFactory
import org.springframework.http.ProblemDetail
import org.springframework.http.ResponseEntity
import org.springframework.validation.annotation.Validated
import org.springframework.web.bind.annotation.PathVariable
import org.springframework.web.bind.annotation.PutMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import io.swagger.v3.oas.annotations.parameters.RequestBody as OpenApiRequestBody

private const val BASIC_RESUME_EXAMPLE = """
    {
        "title": "Software Engineer Resume",
        "content": {
            "basics": {
                "name": "John Doe",
                "email": "john.doe@example.com",
                "label": "Senior Software Engineer",
                "phone": "+1-555-0123",
                "summary": "Experienced engineer with a focus on cloud-native apps."
            },
            "work": [
                {
                    "name": "Tech Corp",
                    "position": "Senior Developer",
                    "startDate": "2020-01-01"
                }
            ],
            "skills": [
                {
                    "name": "Web Development",
                    "keywords": ["Kotlin", "Spring Boot", "Vue.js"]
                }
            ]
        }
    }
"""

/**
 * Controller for creating new resume/CV documents.
 *
 * This controller handles the creation of resume documents within a workspace context.
 * The workspace ID is obtained from the X-Workspace-Id header.
 *
 * Uses header-based API versioning (API-Version: v1).
 *
 * ## Security Features:
 * - Requires authentication (Bearer JWT token)
 * - Requires workspace context (X-Workspace-Id header)
 * - Validates user access to workspace
 * - Uses Row-Level Security (RLS) for data isolation
 *
 * @property mediator The mediator for dispatching commands.
 * @created 20/11/25
 */
@Validated
@RestController
@RequestMapping(value = ["/api"], produces = ["application/vnd.api.v1+json"])
@Tag(
    name = "Resume",
    description = "Resume/CV document management endpoints",
)
class CreateResumeController(
    mediator: Mediator,
) : ApiController(mediator) {
    /**
     * Creates a new resume/CV document.
     *
     * Creates a resume with the specified ID, title, and content within the current workspace.
     * The resume ID must be a valid UUID and should be generated by the client.
     * The workspace context is determined from the X-Workspace-Id header.
     *
     * @param id The UUID for the new resume (client-generated).
     * @param request The resume creation request containing title and content.
     * @return ResponseEntity with HTTP 201 Created and the created resume document.
     */
    @Operation(
        summary = "Create a new resume/CV document",
        description = "Creates a new resume within a workspace context. " +
            "The resume ID must be a UUID generated by the client to ensure idempotency and " +
            "enable offline-first capabilities. Requires workspace context via the X-Workspace-Id header.",
        security = [SecurityRequirement(name = "bearerAuth")],
        parameters = [
            Parameter(
                name = "id",
                description = "The unique UUID for the new resume (client-generated)",
                required = true,
                `in` = ParameterIn.PATH,
                example = "550e8400-e29b-41d4-a716-446655440000",
            ),
            Parameter(
                name = "X-Workspace-Id",
                description = "The ID of the workspace where the resume will be created",
                required = true,
                `in` = ParameterIn.HEADER,
                schema = Schema(type = "string", format = "uuid"),
                example = "123e4567-e89b-12d3-a456-426614174000",
            ),
        ],
    )
    @ApiResponses(
        value = [
            ApiResponse(
                responseCode = "201",
                description = "Resume created successfully - Location header contains resume URI",
                content = [
                    Content(
                        mediaType = "application/vnd.api.v1+json",
                        schema = Schema(implementation = ResumeDocumentResponse::class),
                    ),
                ],
            ),
            ApiResponse(
                responseCode = "400",
                description = "Invalid request data or missing X-Workspace-Id header",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "401",
                description = "Unauthorized - Missing or invalid authentication token",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "403",
                description = "Forbidden - User does not have access to the specified workspace",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "409",
                description = "Conflict - Resume with the specified ID already exists",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
            ApiResponse(
                responseCode = "500",
                description = "Internal server error during resume creation",
                content = [Content(schema = Schema(implementation = ProblemDetail::class))],
            ),
        ],
    )
    @PutMapping("/resume/{id}", consumes = ["application/json"])
    suspend fun createResume(
        @PathVariable id: UUID,
        @Valid
        @OpenApiRequestBody(
            description = "Resume creation data following JSON Resume schema",
            required = true,
            content = [
                Content(
                    mediaType = "application/json",
                    schema = Schema(implementation = CreateResumeRequest::class),
                    examples = [
                        ExampleObject(
                            name = "Basic Resume",
                            summary = "A simple resume with basic information and skills",
                            value = BASIC_RESUME_EXAMPLE,
                        ),
                    ],
                ),
            ],
        )
        @RequestBody request: CreateResumeRequest,
    ): ResponseEntity<ResumeDocumentResponse> {
        val safeIdMasked = LogMasker.mask(id)
        log.debug("Creating new resume: {}", safeIdMasked)

        val userId = userIdFromToken()
        val workspaceId = workspaceIdFromContext()

        val command = CreateResumeCommand(
            id = id,
            userId = userId,
            workspaceId = workspaceId,
            title = request.title,
            content = ResumeRequestMapper.toDomain(request.content),
            createdBy = userId.toString(),
        )

        val response = try {
            dispatch(command)
        } catch (e: CommandHandlerExecutionError) {
            log.error("Error creating resume/cv with ID: {}", safeIdMasked, e)
            throw e
        }

        log.info("Resume created successfully with ID: {}", safeIdMasked)

        return ResponseEntity.created(
            URI.create("/api/resume/${sanitizePathVariable(id.toString())}"),
        ).body(response)
    }

    companion object {
        private val log = LoggerFactory.getLogger(CreateResumeController::class.java)
    }
}
