package com.cvix

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.EnableAutoConfiguration
import org.springframework.boot.context.properties.ConfigurationPropertiesScan

@SpringBootConfiguration
@EnableAutoConfiguration
@ConfigurationPropertiesScan
open class TestApplication
