name: Setup Docker Buildx
description: Set up QEMU and Docker Buildx for multi-platform builds

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca
      with:
        version: v0.12.0
        driver-opts: |
          image=moby/buildkit:v0.12.5
