name: Setup Docker Buildx
description: Set up QEMU and Docker Buildx for multi-platform builds

runs:
  using: composite
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        version: v0.12.0
        driver-opts: |
          image=moby/buildkit:v0.12.5
